services:
  tinymediamanager:
    image: lzwang/tmm:3.1.18
    container_name: tinymediamanager
    restart: always
    ports:
      - "5800:5800"
      - "5900:5900"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=Asia/Shanghai
      - KEEP_APP_RUNNIN=1
    volumes:
      - "./data:/config/data:rw"
      - "./media:/media:rw"
